spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crud?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: gaodi

    druid:

      stat-view-servlet:
        enabled: true
        login-username: will
        login-password: gaodi
        reset-enable: false

      web-stat-filter:
        enabled: true
        url-pattern: /*

      filters: stat,wall,slf4j

      aop-patterns: com.example.springbootcrud.*

      filter:
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true
        slf4j:
          enabled: true
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  mvc:
    hiddenmethod:
      filter:
        enabled: on

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
#redis配置
  redis:
    host: localhost
    port: 6379

mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.example.springbootcrud.pojo
logging:
  level:
    root: info

server:
  port: 8080